# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muxforge < Formula
  desc "A plugin manager and multiplexer forge for developer toolchains"
  homepage "https://github.com/TechAlchemistX/muxforge"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TechAlchemistX/muxforge/releases/download/v0.2.0/muxforge-darwin-amd64.tar.gz"
      sha256 "dd43940c107ecd406300cb916738ea6e230db8b439bf0330b7dcac64a1c7adde"

      define_method(:install) do
        bin.install "muxforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TechAlchemistX/muxforge/releases/download/v0.2.0/muxforge-darwin-arm64.tar.gz"
      sha256 "9792d00e68cf84383af5ea97fdab9ae0d32e940c07947681582493dcc8f69758"

      define_method(:install) do
        bin.install "muxforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TechAlchemistX/muxforge/releases/download/v0.2.0/muxforge-linux-amd64.tar.gz"
      sha256 "0cdb4521da99fe3cc5e1c4e02b71f8ea03ab760afe0135a79872b976ce025e89"
      define_method(:install) do
        bin.install "muxforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TechAlchemistX/muxforge/releases/download/v0.2.0/muxforge-linux-arm64.tar.gz"
      sha256 "a76bd7947d36e3e8659944daaf08fa49568467a65017199fd2106501eb3c65fc"
      define_method(:install) do
        bin.install "muxforge"
      end
    end
  end

  test do
    assert_match /muxforge v/, shell_output("#{bin}/muxforge --version")
  end
end
