# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muxforge < Formula
  desc "A plugin manager and multiplexer forge for developer toolchains"
  homepage "https://github.com/TechAlchemistX/muxforge"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TechAlchemistX/muxforge/releases/download/v0.4.0/muxforge-darwin-amd64.tar.gz"
      sha256 "870513dd90c8a42f91d708fe51188afd8850946f0d0b4dbc3bc80ffdf97f1755"

      define_method(:install) do
        bin.install "muxforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TechAlchemistX/muxforge/releases/download/v0.4.0/muxforge-darwin-arm64.tar.gz"
      sha256 "dbc6318a5238f593f4da61addb84defe718732d31a6099076a9b8a514035b0f3"

      define_method(:install) do
        bin.install "muxforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TechAlchemistX/muxforge/releases/download/v0.4.0/muxforge-linux-amd64.tar.gz"
      sha256 "13b543e1a6be46da7b1bd69ee852ffcfe49fdd9478aaa4cba844d2d39601ee1e"
      define_method(:install) do
        bin.install "muxforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TechAlchemistX/muxforge/releases/download/v0.4.0/muxforge-linux-arm64.tar.gz"
      sha256 "4286d27b01e2608da313e9df004569681ee24bdc3e902e430e601e71261ebe86"
      define_method(:install) do
        bin.install "muxforge"
      end
    end
  end

  def caveats
    <<~EOS
      To clean up tmux.conf before uninstalling, run:
        muxforge purge

      To also remove all plugin directories:
        muxforge purge --purge-plugins
    EOS
  end

  test do
    assert_match /muxforge v/, shell_output("#{bin}/muxforge --version")
  end
end
